### ISSUE TITLE
where do you even put in the token

### ISSUE THREAD

**Issue by suptrpls** [DuckoDas/DJS-Suggestion-System-v14#1]

**Comment by cartiqo** [comment]
You need to already have a bot for this but i have another repo called FullDiscordBot which includes this system and ticket system

**Comment by suptrpls** [comment]
> You need to already have a bot for this but i have another repo called FullDiscordBot which includes this system and ticket system
Do you think you can make it automaticity makes a suggestion to whoever types in a certain channel that's been put in

**Comment by cartiqo** [comment]
> 

Yeah i can probably do so in the future
